### Registration ###
POST http://localhost:8082/auth/registration
Content-Type: application/json

{
  "name": "Alijon",
  "surname": "Alliyev",
  "phone": "3333333",
  "password": "7777",
  "email": "raufovmaruf444@gmail.com"
}



### Authorization user token
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "phone": "555555",
  "password": "44444"
}

### Authorization Admin token
POST localhost:8081/auth/login
Content-Type: application/json

{
  "phone": "+998932222077",
  "password": "22222"
}