### Registration ###
POST http://localhost:8082/auth/registration
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Valiyev",
  "phone": "6700",
  "password": "2700",
  "email": "alivaliy@gmail.com"
}
### Authorization user token
POST http://localhost:8082/auth/login
Content-Type: application/json

{
  "phone": "6700",
  "password": "2700"
}

### Authorization Admin token
POST localhost:8082/auth/login
Content-Type: application/json

{
  "phone": "+998932222077",
  "password": "22222"
}