### Category Create
POST http://localhost:8081/category/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDMxNjAwOTUsInBob25lIjoiKzk5ODkzMjIyMjA3NyIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzAzMjQ2NDk1LCJpc3MiOiJTZWN1cml0eSJ9.qA3nObd1-83O--RSaDFlfgkuCjjucG6fZzFoXKlLuJbsTyjPO56jYffLb4FQaca-SN4HGJ2nUn6wO8YTDu3KCg

{
  "key": "0000000",
  "nameUz": "yetti",
  "nameRu": "sem",
  "nameEn": "seven"
}



### Update

PUT http://localhost:8081/category/update/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDI3NTA0ODIsInBob25lIjoiKzk5ODkzMjIyMjA3NyIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzAyODM2ODgyLCJpc3MiOiJTZWN1cml0eSJ9.Xc7TjKyh1kvHE0dqvPxqd-CU5lgBmUuE4onsMhx2nLmrYSHGa6cPm9fjW0DDRdkaIXoDGc3mKdr8O1S_V5jk4A

{
  "key": "gulica",
  "nameUz": "xaxa😃 toshkentdaman",
  "nameRu": "😁 pogoda ",
  "nameEn": "Today 😇🤗 very good",
  "visible":true
}

### DETELE Admin category
PUT http://localhost:8081/category/delete/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDI3NTA0ODIsInBob25lIjoiKzk5ODkzMjIyMjA3NyIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzAyODM2ODgyLCJpc3MiOiJTZWN1cml0eSJ9.Xc7TjKyh1kvHE0dqvPxqd-CU5lgBmUuE4onsMhx2nLmrYSHGa6cPm9fjW0DDRdkaIXoDGc3mKdr8O1S_V5jk4A


### Get list
GET http://localhost:8081/category/list?page=0&size=1

### Get Language
GET http://localhost:8081/category/byLang?lang=RU



